name: Package
on: push
jobs:
  pack-arch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker://archlinux:latest
        with:
            args: echo hello

  pack-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: rundock
        run: |
            docker ps
            docker images
            docker run debian echo hello

